services:
  mifosx:
    build:
      context: ./mifos
      dockerfile: Dockerfile
    container_name: mifosx
    restart: unless-stopped
    ports:
      - '8443:8443'
    networks:
      - mifos-network
    depends_on:
      mifos-db-server:
        condition: service_healthy
      
  mifos-db-server:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mifos-db
    restart: unless-stopped
    ports:
      - '3307:3306'
    healthcheck:
      test: mysqladmin --user=$MYSQL_ROOT --password=$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 5s
      retries: 20
    volumes:
      - 'dbdata:/var/lib/mysql'
    env_file:
      - .env_sql
    networks:
      - mifos-network

  mifos_phpmyadmin:
    links:
      - mifos-db-server
    image: phpmyadmin/phpmyadmin
    container_name: mifos_phpmyadmin
    restart: unless-stopped
    ports:
      - '8095:80'
    environment:
      PMA_PORT: 3306
      PMA_HOST: mifos-db-server
      UPLOAD_LIMIT: 1000000000
    networks:
      - mifos-network

networks:
  mifos-network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.130.0/29"
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      device: /home/rits/freelancer/mifos-docker-master/data
      o: bind
